---
title: "Functional Programming - Exercises 2"
author: "Aksel Thomsen"
date: "Statistical Programming with R"
output: html_document
---

There is four problems 

## Problem 7

On the `mtcars` estimate the following linear model:

$qsec = a \cdot hp + b \cdot wt$

So where the time in seconds to complete a quarter-mile (`qsec`) is a linear function of horsepower (`hp`) and weight in 1,000 lbs (`wt`). Hint: use the `lm` function.

Afterwards extract the coefficient (`a` & `b` in the equation) into seperate variables.
Hint: Experiment with the `coef` function.

**Solution**

## Problem 8

Divide the `mtcars` data in subsets based on the number of gears (`gear`) each car has.

Now estimate the same model from Problem 7, but this time estimate one individual model for each of these subset.

Finally compare the results.

**Solution**

## Problem 9

Using the `mydata_example` data from yesterday:

```{r, message=FALSE}
library(tidyverse)
load("mydata_example.Rda")

mydata_example <- as_tibble(mydata_example)
mydata_example
```

Draw a simple stratified sample with the following specifications:

- Sample size: 200
- Strata: `region` & `sector`
- Proportional allocation

**Solution**

## Problem 10

In stead of proportional allocation can you draw a sample with optimal allocation based on the variance of `turnover_2019`?
Otherwise the same specifications as Problem 9.

**Solution**